import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Avatar, Card, List, Tooltip } from 'antd';
import { BadgeCheck, Briefcase, Edit, Eye, Mail, MapPin, ShieldAlert, ShieldCheck, Trash2 } from 'lucide-react';
function GridView({ tableData, isLoading, pagination, handleView, handleEdit, handleDelete, default_doctor }) {
    return (_jsx(List, { grid: { gutter: 16, xs: 1, sm: 2, md: 2, lg: 3, xl: 4, xxl: 4 }, dataSource: tableData, loading: isLoading, pagination: pagination, renderItem: (item) => (_jsx(List.Item, { children: _jsx(Card, { className: "rounded-xl overflow-hidden border-gray-100 shadow-sm", bodyStyle: { padding: "20px" }, actions: [
                    _jsx(Tooltip, { title: "View", children: _jsx(Eye, { size: 18, className: "mx-auto text-blue-500", onClick: () => handleView(item) }) }),
                    _jsx(Tooltip, { title: "Edit", children: _jsx(Edit, { size: 18, className: "mx-auto text-green-500", onClick: () => handleEdit(item) }) }),
                    _jsx(Tooltip, { title: "Delete", children: _jsx(Trash2, { size: 18, className: "mx-auto text-red-500", onClick: () => handleDelete(item) }) }),
                ], children: _jsxs("div", { className: "flex flex-col items-center", children: [_jsxs("div", { className: "relative mb-3", children: [_jsx(Avatar, { size: 70, src: item.profile_photo || default_doctor, className: "border-2 border-white shadow-sm" }), _jsx("div", { className: "absolute bottom-1 -right-1 bg-white rounded-full p-0.5", children: item.is_active ? (_jsx(ShieldCheck, { size: 18, className: "text-green-500 bg-white rounded-full" })) : (_jsx(ShieldAlert, { size: 18, className: "text-red-500 bg-white rounded-full" })) })] }), _jsxs("div", { className: "text-center mb-4", children: [_jsxs("h4", { className: "m-0 font-bold text-gray-800 flex items-center justify-center gap-1 text-base", children: [item.name, " ", item.is_verify === 1 && (_jsx(BadgeCheck, { size: 16, className: "text-blue-500" }))] }), _jsx("span", { className: "text-blue-600 text-xs font-semibold uppercase tracking-wider", children: item.specialization })] }), _jsxs("div", { className: "w-full space-y-2 text-xs text-gray-500 pt-3 border-t border-gray-50", children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsx(Mail, { size: 14 }), " ", _jsx("span", { className: "truncate", children: item.email })] }), _jsxs("div", { className: "flex items-center gap-2", children: [_jsx(Briefcase, { size: 14 }), " ", _jsxs("span", { children: [item.experience, " yrs Experience"] })] }), _jsxs("div", { className: "flex items-center gap-2", children: [_jsx(MapPin, { size: 14 }), " ", _jsx("span", { className: "truncate", children: item.address || "-" })] })] })] }) }) })) }));
}
export default GridView;
